class FunctionNames:
    RUN_INTEGRATIONS_POST_WORKFLOW_RUN = "run_integrations_post_workflow_run"
    PROCESS_WORKFLOW_COMPLETION = "process_workflow_completion"
    SYNC_CAMPAIGN_SOURCE = "sync_campaign_source"
    PROCESS_CAMPAIGN_BATCH = "process_campaign_batch"
    PROCESS_KNOWLEDGE_BASE_DOCUMENT = "process_knowledge_base_document"
    POLL_META_LEADS = "poll_meta_leads"
    PROCESS_DUE_ENROLLMENTS = "process_due_enrollments"
    DELIVER_WEBHOOK = "deliver_webhook"
    COMPLETE_INACTIVE_TEXT_CHAT_SESSION = "complete_inactive_text_chat_session"
